wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.17.4
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721755640
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.11.1
      5: 0.17.4
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
